version: "3"
services:
  postgres:
    image: postgres:12.3-alpine
    restart: always
    networks:
      - taskcafe-test
    environment:
      POSTGRES_USER: taskcafe
      POSTGRES_PASSWORD: taskcafe_test
      POSTGRES_DB: taskcafe
    volumes:
      - taskcafe-postgres:/var/lib/postgresql/data
    ports:
      - 8855:5432
  mailhog:
    image: mailhog/mailhog:latest
    restart: always
    ports:
      - 1025:1025
      - 8025:8025
  broker:
    image: rabbitmq:3-management
    restart: always
    ports:
      - 8060:15672
      - 5672:5672
  result_store:
    image: memcached:1.6-alpine
    restart: always
    ports:
      - 11211:11211

volumes:
  taskcafe-postgres:
    external: false

networks:
  taskcafe-test:
    driver: bridge
